name: hello
run-name: ${{ github.actor }} is saying hello to GitHub Actions
on: [push]
jobs:
  hello-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/hello
      # - name: logging hello world step
      #   run: echo "Hello World!"
